### ISSUE TITLE
"Poster" throws error 

### ISSUE THREAD

**Issue by DannyChristy** [Ironholds/poster#10]
I am trying to integrate libpostal with R using the package Poster. I have successfully installed libpostal and Poster in my machine. However i could not use any methods like poster::city("hansastrasse 84, 24118 kiel") or  poster::house("hansastrasse 84, 24118 kiel") . and the error is 
Error in get_elements_(x, 5) : 
  attempt to set index 10/10 in SET_STRING_ELT

Could you please help me out ?

**Comment by Ironholds** [comment]
I'll look into it,

**Comment by DannyChristy** [comment]
Thanks a ton !

**Comment by Ironholds** [comment]
Try with the latest version?

**Comment by Ironholds** [comment]
@DannyChristy ?

**Comment by Ironholds** [comment]
Whelp, this seems fixed at my end.
