### ISSUE TITLE
[31mERR[39m   Error loading transliteration module, dir=(null)

### ISSUE THREAD

**Issue by JonnoB** [Ironholds/poster#11]
Hi 

I am installing poster on Ubuntu 17.04 and R 3.4.0, I get the following error.
```r
** R
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
[31mERR[39m   Error loading transliteration module, dir=(null)
  [90m at libpostal_setup_datadir (libpostal.c:1088) [94merrno: Not a directory[39m
Error: package or namespace load failed for ‘poster’:
 .onLoad failed in loadNamespace() for 'poster', details:
  call: setup()
  error: Libbpostal setup failed
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/jonno/R/x86_64-pc-linux-gnu-library/3.4/poster’
Installation failed: Command failed (1)
```

Any help would be appreciated

Thanks!

Jonno

**Comment by thatdatabaseguy** [comment]
Hi @JonnoB - that sounds like something weird happened during the libpostal install e.g. the library is installed/linked correctly, but the data download didn't complete. Try reinstalling libpostal, making sure that the location you specified for `--datadir` during configure exists, has at least 1.8G of free space (as of version 1.0, that number may change in subsequent versions), and that the `make` command runs successfully.

**Comment by JonnoB** [comment]
A reinstall was all it took, it works great now, thanks for the help!
