### ISSUE TITLE
Write a proper autoconf script

### ISSUE THREAD

**Issue by Ironholds** [Ironholds/poster#3]
The last blocker until release - a script that actually checks for the presence of libpostal and stops if it can't be found.

**Comment by Ironholds** [comment]
I actually succeeded. Huh!

**Comment by thatdatabaseguy** [comment]
Hm, with autoconf (not an expert but it's what I use for libpostal) usually one would just check in configure.ac, then have to run ```autoreconf``` to generate the configure script. If it's just checking for an installed header, autoconf might be overkill.

Just pushed a branch called [simple-configure](https://github.com/Ironholds/poster/tree/simple-configure) which uses the Anticonf script from Jeroen Ooms (seen in many R packages with bindings to installed C libs). Can use or not, as you prefer.

**Comment by Ironholds** [comment]
Oh nice! Yeah, merge that into master, that's awesome!

**Comment by Ironholds** [comment]
I've decided Jeroen is the only human being who knows how autoconf works on the entire planet. That shit is some lovecraftian nightmare best written by turning your keyboard keyside-down and bashing it against the table with a text processor open.

**Comment by thatdatabaseguy** [comment]
Done.

And agreed. For C libs autotools remains a necessary evil for getting into OS package managers, but in most higher level languages there's already some cross-platform fu built in, so a pkg-config one-liner is usually all that's needed.
