### ISSUE TITLE
Installing Poster Problems

### ISSUE THREAD

**Issue by UrbanPlanner42** [Ironholds/poster#7]
Hi, 

First, thank you for making this binding in R. I am trying to install poster, but I am running into an issue. Already installed all dependencies and libpostal.  Even though, I am running into this error. 

I am not sure where is the error.  If you can help me to point the problem, it will be great. 

Thank you,
Alex 

```> devtools::install_github("ironholds/poster")
Downloading GitHub repo ironholds/poster@master
from URL https://api.github.com/repos/ironholds/poster/zipball/master
Installing poster
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/bp/w10f290n0cg6kg8__z58k28dfvh41r/T/RtmpuYFgtt/devtools17f364bb8da09/Ironholds-poster-90044cd'  \
  --library='/Library/Frameworks/R.framework/Versions/3.3/Resources/library' --install-tests 

* installing *source* package ‘poster’ ...
Found pkg-config cflags and libs!
Using PKG_CFLAGS=-I/usr/local/include
Using PKG_LIBS=-L/usr/local/lib -lpostal
** libs
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I/usr/local/include -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I/usr/local/include -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c postal.cpp -o postal.o
In file included from postal.cpp:1:
./postal.h:15:42: error: unknown type name 'address_parser_options_t'
  CharacterVector parse_single(String x, address_parser_options_t& opts);
                                         ^
postal.cpp:33:57: error: unknown type name 'address_parser_options_t'
CharacterVector poster_internal::parse_single(String x, address_parser_options_t& opts){
                                                        ^
postal.cpp:111:3: error: unknown type name 'normalize_options_t'
  normalize_options_t options = libpostal_get_default_options();
  ^
postal.cpp:174:7: error: unknown type name 'address_parser_response_t'
      address_parser_response_t *parsed = libpostal_parse_address((char*) addresses[i],
      ^
postal.cpp:262:47: error: use of undeclared identifier 'postcode'
                           _["postal_code"] = postcode,
                                              ^
5 errors generated.
make: *** [postal.o] Error 1
ERROR: compilation failed for package ‘poster’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/poster’
Error: Command failed (1)```

**Comment by Ironholds** [comment]
Heya! Sorry about that. Try now?

**Comment by UrbanPlanner42** [comment]
Thank you for getting back to me so quickly.   Sadly, I still have a problem in installing the R binding. I was able to run libpostal using python in the terminal.  Here is the error:

```
1 error generated.
make: *** [postal.o] Error 1
ERROR: compilation failed for package ‘poster’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/poster’
Error: Command failed (1)
```

**Comment by thatdatabaseguy** [comment]
Well, that's one way to implement varargs :-).

Incidentally, one of the first articles that comes up in Googling the 20-arg limit is https://ironholds.org/blog/creating-large-data-frames-in-rcpp/. So I take it something like [this](https://github.com/Ironholds/rgeolocate/blob/master/src/ip2.cpp#L415-L418) is needed @Ironholds?

**Comment by Ironholds** [comment]
Iiindeed. I'll put this bugfix next on my to-do list and see if I can't tidy up some of the code while I'm there.

**Comment by tchakravarty** [comment]
Same issue, I also have `libpostal` installed, in a non-standard location. While I was able to get [`Rpostal`](https://github.com/Datactuariat/Rpostal) working by using the `libpostal_path` argument to its functions, since `poster` looks for the installation of `libpostal` at install time, I was not able to get it to work.

**Comment by Ironholds** [comment]
By nonstandard location do you mean it's not on the lconfig path, or?

**Comment by UrbanPlanner42** [comment]
@Ironholds @thatdatabaseguy   I was wondering if I have libpostal in a specific directory so that poster can find it during the installation?

**Comment by Ironholds** [comment]
What operating system are you using?

**Comment by UrbanPlanner42** [comment]
I am Mac OS X

**Comment by Ironholds** [comment]
Where and how are you installing it?

**Comment by UrbanPlanner42** [comment]
/Users/asoto/projects/packages/libpostal

**Comment by Ironholds** [comment]
Well, I can't speak to whether brew actually configures the linking flags properly, but to be clear the current bug you're running into is entirely unrelated to install location - it's a limitation of my current C++ binding, and one I hope to correct this evening.

**Comment by Ironholds** [comment]
The current repo shoould fix your problem. Let me know if it reappears. Fix aside, though, the code is now looking hella gross and I need to clean it up.

**Comment by UrbanPlanner42** [comment]
Success, thank you!!
