### ISSUE TITLE
linux installation failure

### ISSUE THREAD

**Issue by stoddn** [Ironholds/poster#9]
Hi,

Failing to install on Fedora 25 , R 3.4.0  and Ubuntu 17.04 R 3.3.2 with same result:

** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/lib/R/site-library/poster/libs/poster.so':
  libpostal.so.1: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed

Thanks,
Todd

**Comment by Ironholds** [comment]
Hey Todd. Did you install and link libpostal separately before installing poster?

**Comment by stoddn** [comment]
Hi Oliver,

I  did install libpostal separately, and have verified that it works using command line in bash. 

Please clarify 'link' though. 

Thanks

**Comment by Ironholds** [comment]
`sudo ldconfig` in this case!

What are the outputs of:

```
pkg-config --cflags libpostal    
pkg-config --libs libpostal    
```
?

**Comment by stoddn** [comment]
Away, but will get back to you in an hour or so.

**Comment by Ironholds** [comment]
Cool!

**Comment by stoddn** [comment]
ldconfig appears to be the fix for Ubuntu, here's output:

# ldconfig -p | grep libpostal
	libpostal.so.1 (libc6,x86-64) => /usr/local/lib/libpostal.so.1
	libpostal.so (libc6,x86-64) => /usr/local/lib/libpostal.so
# pkg-config --libs libpostal  
-L/usr/local/lib -lpostal
# pkg-config --cflags libpostal
-I/usr/local/include

Still working on Fedora ...

**Comment by Ironholds** [comment]
Neat! Lemme know what happens with Fedora and what the pkg-config results look like there.

**Comment by stoddn** [comment]
Here's what's needed for Fedora:

1. create or edit /etc/ld.so.conf.d/local.conf and a line: add /usr/local/lib
2. then run ldconfig
3. then ldconfig -p | grep libpostal shows:

	libpostal.so.1 (libc6,x86-64) => /usr/local/lib/libpostal.so.1
	libpostal.so (libc6,x86-64) => /usr/local/lib/libpostal.so


For whatever reason the pkg-config commands won't find libpostal. But the install works anyway despite the warnings:

  Package libpostal was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libpostal.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libpostal' found

Setting PKG_CONFIG_PATH does allow pkg-config to find libpostal.

Thanks again,
Todd

**Comment by Ironholds** [comment]
No problem!
